name: Open PR into main

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Angular Docker image
        run: |
          cd frontend
          docker build -t angular-test:${{ github.sha }} .

      - name: Build .NET Docker image
        run: |
          cd backend
          dotnet build -t dotnet-test:${{ github.sha }} .
      
      - name: Build verification passed
        run: echo "Both images built successfully"